# Generated by Django 3.2.3 on 2021-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, unique=True, upload_to=''),
            preserve_default=False,
        ),
    ]
