# Generated by Django 3.2.3 on 2021-05-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='type',
            new_name='session',
        ),
        migrations.AddField(
            model_name='file',
            name='round_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.CharField(default=2020, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(unique=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'year', 'session', 'round_number')},
        ),
        migrations.AlterIndexTogether(
            name='file',
            index_together={('name', 'year', 'session', 'round_number')},
        ),
    ]
