# Generated by Django 3.2.3 on 2021-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20210518_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='track',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'year', 'session', 'round_number', 'championship', 'track')},
        ),
        migrations.AlterIndexTogether(
            name='file',
            index_together={('name', 'year', 'session', 'round_number', 'championship', 'track')},
        ),
    ]
