# Generated by Django 3.2.3 on 2021-05-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20210518_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
