# Generated by Django 3.2.3 on 2021-05-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210517_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
