# Generated by Django 3.2.3 on 2021-05-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_driver_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='nationality',
            new_name='nat',
        ),
    ]
