# Generated by Django 3.2.3 on 2021-05-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_result_mph'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='position_in_class',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='road_condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.roadcondition'),
            preserve_default=False,
        ),
    ]
