# Generated by Django 3.2.3 on 2021-05-20 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210519_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='weather',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.weather'),
            preserve_default=False,
        ),
    ]
