# Generated by Django 3.2.3 on 2021-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date_of_event',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='time_of_event',
            field=models.TimeField(),
        ),
    ]
