# Generated by Django 3.2.3 on 2021-05-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210520_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
